App_order/urls.py
from django.urls import path
from . import views

app_name = 'App_order'

urlpatterns = [
    path('add_to_cart/<pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('increase/<pk>/', views.increase_quantity, name='increase'),
    path('decrease/<pk>/', views.decrease_quantity, name='decrease'),
    path('remove_item/<pk>/', views.remove_item, name='remove_item')
]

App_shop/urls.py
from django.urls import path
from . import views

app_name = 'App_shop'

urlpatterns = [
    path('add_product/', views.add_product, name='add_product'),
    path('', views.all_product, name='home'),
    path('product_details/<pk>/', views.product_details, name='product_details'),
    path('sellar_product/',views.view_sellar_product,name='sellar_product')
]

multivendor_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('App_login.urls'), namespace='App_login')),
    path('', include(('App_shop.urls'), namespace='App_shop')),
    path('shop/', include(('App_order.urls'), namespace='App_order')),
    path('payment/', include(('App_payment.urls'), namespace='App_payment'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_shop/models.py
from django.db import models
from App_login.models import Sellar

# Create your models here.


class Catagory(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Catagories'


class Product(models.Model):
    catagory = models.ForeignKey(
        Catagory, on_delete=models.CASCADE, related_name='product_catagory')

    sellar = models.ForeignKey(
        Sellar, on_delete=models.CASCADE, related_name='product_sellar')
    product_image = models.ImageField(upload_to='product_image')
    product_name = models.CharField(max_length=255)
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    short_text = models.CharField(max_length=40)
    product_description = models.TextField(verbose_name='product discription')
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name

App_shop/forms.py
from django.forms import ModelForm
from .models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ['sellar']

App_shop/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from App_login.models import Sellar
from App_shop.models import Product
from .forms import ProductForm

# Create your views here.


@login_required
def add_product(request):
    sellar = Sellar.objects.filter(user=request.user)[0]
    form = ProductForm()

    if sellar is not None and sellar.is_fully_filled():
        if request.method == 'POST':
            form = ProductForm(request.POST, request.FILES)
            if form.is_valid():
                add_product = form.save(commit=False)
                add_product.sellar = sellar
                add_product.save()
                messages.success(request, 'Product Added Successfully !')
    else:
        messages.success(request, 'Please fill up All Details')
        return HttpResponseRedirect(reverse('App_login:sellar'))

    return render(request, 'App_shop/add_product.html', context={'form': form})


def all_product(request):
    all_products = Product.objects.all().order_by('-create_at')

    return render(request, 'App_shop/home.html', context={'all_products': all_products})


def product_details(request, pk):
    product = get_object_or_404(Product, pk=pk)

    return render(request, 'App_shop/product_details.html', context={'product': product})


@login_required
def view_sellar_product(request):
    sellar = Sellar.objects.filter(user=request.user)
    if sellar.exists():
        products = Product.objects.filter(sellar=sellar[0])
        if not products.exists():
            messages.warning(request,'You Have No Product !')
            return HttpResponseRedirect(reverse('App_shop:home'))


    else:
        messages.warning(request, 'You Are Not Our Sellar !')
        return HttpResponseRedirect(reverse('App_shop:home'))

    return render(request, 'App_shop/sellar_product.html', context={'products':products})

templates/App_shop/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    Add Product
{% endblock title %}


{% block body_block %}
<h1 class="text-center">Add Product</h1>
<form action="" method="post" enctype="multipart/form-data" class="my-4">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Add Product" class="btn btn-success">
</form>
    
{% endblock body_block %}
    

templates/App_shop/home.html
{% extends 'base.html' %}


{% block title %}
Home
{% endblock title %}


{% block body_block %}
<div class="row">
    {% for product in all_products %}
    <div class="product">


        <a href="{% url 'App_shop:product_details' pk=product.pk %}"><img src="{{product.product_image.url}}" alt=""
                width="100%" height="300px"></a>



        <a href="{% url 'App_shop:product_details' pk=product.pk %}" class="text-decoration-none mt-2">
            <h6>{{product.product_name}}</h6>
        </a>
        <div class="d-flex justify-content-between">

            <p>&#2547; <strong>{{product.price}}</strong> <strike>{{product.old_price}}</strike></p>

            <a href="{% url 'App_order:add_to_cart' pk=product.pk%}" title="add to cart"><i class="fa-solid fa-cart-shopping"></i></a>
        </div>


    </div>





    {% endfor %}
</div>

{% endblock body_block %}

templates/App_shop/product_details.html
{% extends 'base.html' %}


{% block title %}
{{product.product_name}}
{% endblock title %}


{% block body_block %}

<div class="row">
    <div class="col-5">
        <img src="{{product.product_image.url}}" alt="" width="100%">
    </div>
    <div class="col-7">
        <h3>{{product.product_name}}</h3>
        <h2 class="text-warning">Tk {{product.price}}</h2>
        <h4>Product Description</h4>
        <p>{{product.product_description|linebreaks}}</p>
        <a href="{% url 'App_order:add_to_cart' pk=product.pk%}" class="btn btn-outline-primary">ADD TO CART <i class="fa-solid fa-cart-shopping"></i></a>



        <div class="mt-4">
            <h4>Contact Sellar</h4>
            <h5>Sellar name : {{product.sellar.user.user_profile.fullname}}</h5>
            <h6>Phone: {{ product.sellar.user.user_profile.phone }}</h6>
        </div>
    </div>
</div>

{% endblock body_block %}

templates/App_shop/sellar_product.html
{% extends 'base.html' %}

{% block title %}
    Your Product
{% endblock title %}


{% block body_block %}

    
<div class="row">
    {% for product in products %}
    <div class="product">


        <a href="{% url 'App_shop:product_details' pk=product.pk %}"><img src="{{product.product_image.url}}" alt=""
            width="100%" height="300px"></a>



        <a href="{% url 'App_shop:product_details' pk=product.pk %}" class="text-decoration-none mt-2">
            <h6>{{product.product_name}}</h6>
        </a>
        <p>&#2547; <strong>{{product.price}}</strong> <strike>{{product.old_price}}</strike></p>

    </div>





    {% endfor %}
</div>

{% endblock body_block %}