App_payment/urls.py
from django.urls import path
from . import views

app_name = 'App_payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='pay'),
    path('compleate/', views.compleat, name='compleate'),
    path('purchased/<tran_id>/<val_id>/',
         views.purchased, name='purchased'),
    path('order/', views.order, name='order')
]

App_shop/urls.py
from django.urls import path
from . import views

app_name = 'App_shop'

urlpatterns = [
    path('add_product/', views.add_product, name='add_product'),
    path('', views.all_product, name='home'),
    path('product_details/<pk>/', views.product_details, name='product_details'),
    path('sellar_product/',views.view_sellar_product,name='sellar_product')
]

multivendor_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('App_login.urls'), namespace='App_login')),
    path('', include(('App_shop.urls'), namespace='App_shop')),
    path('shop/', include(('App_order.urls'), namespace='App_order')),
    path('payment/', include(('App_payment.urls'), namespace='App_payment'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_payment/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class BillingAddress(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_billing_address')
    address = models.CharField(max_length=255, null=True, blank=True)
    zip_code = models.CharField(max_length=10, null=True, blank=True)
    city = models.CharField(max_length=10, null=True, blank=True)
    country = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return self.user.user_profile.fullname

    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]
        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

App_payment/forms.py
from django.forms import ModelForm
from .models import BillingAddress


class BillingAddressForm(ModelForm):
    class Meta:
        model = BillingAddress
        exclude = ['user']

App_payment/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from App_order.models import Order, Cart
from App_login.models import Profile
from .forms import BillingAddressForm
from .models import BillingAddress
from sslcommerz_lib import SSLCOMMERZ


# Create your views here.


@login_required
def checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order_items = order_qs[0].order_items.all()
    order_total = order_qs[0].get_totals()
    address_form = BillingAddressForm(instance=saved_address[0])
    if request.method == 'POST':
        address_form = BillingAddressForm(
            data=request.POST, instance=saved_address[0])
        if address_form.is_valid():
            user_address_form = address_form.save(commit=False)
            user_address_form.user = request.user
            user_address_form.save()
            address_form = BillingAddressForm(instance=saved_address[0])
            messages.success(request, 'Address Saved Successfully !')
            return redirect('App_payment:checkout')

    return render(request, 'App_payment/checkout.html', context={'address_form': address_form, 'order_items': order_items, 'order_total': order_total})


@login_required
def payment(request):

    profile = Profile.objects.filter(user=request.user)[0]
    saved_address = BillingAddress.objects.filter(user=request.user)[0]

    if not profile.is_fully_filled():
        messages.warning(
            request, 'Please fill up all profile information first !')
        return redirect('App_login:profile')
    if not saved_address.is_fully_filled():
        messages.warning(request, 'Please fill up all  information first !')
        return redirect('App_payment:checkout')

    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order_total = order_qs[0].get_totals()
    order_count = order_qs[0].order_items.count()
    order_items = order_qs[0].order_items.all()

    store_id = 'ecomm648d7870e47c0'
    api_key = 'ecomm648d7870e47c0@ssl'

    settings = {'store_id': store_id, 'store_pass': api_key, 'issandbox': True}
    sslcommez = SSLCOMMERZ(settings)

    status_url = request.build_absolute_uri(reverse('App_payment:compleate'))
    current_user = request.user

    post_body = {}
    post_body['total_amount'] = order_total
    post_body['currency'] = "BDT"
    post_body['tran_id'] = "12345"
    post_body['success_url'] = status_url
    post_body['fail_url'] = status_url
    post_body['cancel_url'] = status_url
    post_body['emi_option'] = 0
    post_body['cus_name'] = profile.fullname
    post_body['cus_email'] = current_user.email
    post_body['cus_phone'] = profile.phone
    post_body['cus_add1'] = profile.address
    post_body['cus_city'] = profile.city
    post_body['cus_country'] = profile.country
    post_body['shipping_method'] = "Curiar"
    post_body['multi_card_name'] = ""
    post_body['num_of_item'] = order_count
    post_body['product_name'] = order_items
    post_body['product_category'] = "Mixed"
    post_body['product_profile'] = "general"

    post_body['ship_name'] = profile.fullname
    post_body['ship_add1'] = saved_address.address
    post_body['ship_city'] = saved_address.city
    post_body['ship_postcode'] = saved_address.zip_code
    post_body['ship_country'] = saved_address.country

    response = sslcommez.createSession(post_body)
    return redirect(response['GatewayPageURL'])


@csrf_exempt
def compleat(request):
    if request.method == 'POST' or request.method == 'post':
        response = request.POST
        status = response['status']
        if status == 'VALID':
            val_id = response['val_id']
            bank_tran_id = response['bank_tran_id']
            return HttpResponseRedirect(reverse('App_payment:purchased', kwargs={'tran_id': bank_tran_id, 'val_id': val_id}))

        elif status == 'FAILED':
            messages.error(request, 'Payment Failed !')
            return redirect('App_shop:home')

    return render(request, 'App_payment/compleate.html', context={})


@login_required
def purchased(request, tran_id, val_id):
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order = order_qs[0]
    order.ordered = True
    order.order_id = val_id
    order.payment_id = tran_id

    order.save()

    cart_item = Cart.objects.filter(user=request.user, purchased=False)
    for item in cart_item:
        item.purchased = True
        item.save()
    messages.success(request, 'Payment Successfully Compleated !')
    return HttpResponseRedirect(reverse('App_shop:home'))


@login_required
def order(request):
    order_qs = Order.objects.filter(
        user=request.user, ordered=True)

    return render(request, 'App_payment/order.html', context={'order_items': order_qs})

templates/App_payment/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
Payment
{% endblock title %}



{% block body_block %}
<h1> Shiping Address > Checkout</h1>
<div class="row">
    <div class="col-8">
        <form action="" method="post">
            {% csrf_token %}
            {{address_form|crispy}}
            <input type="submit" value="Save" class="btn btn-success">
        </form>

    </div>
    <div class="col-4">
        <div class="card" style="width: 20rem;">
            <ul class="list-group list-group-flush">

                {% for order in order_items %}

                <li class="list-group-item">{{order}}</li>
                {% endfor %}


            </ul>
            <div class="card-footer">
                <h6>SubTotal : {{order_total}}</h6>
            </div>
        </div>

        {% if user.user_billing_address.is_fully_filled %}
        <a href="{% url 'App_payment:pay' %}" class="btn btn-warning mt-4">Make Payment</a>
        {% else %}
        <p class="alert alert-warning mt-3">Fill Up All Information for make payment</p>

        {% endif %}

    </div>
</div>

{% endblock body_block %}

templates/App_payment/compleate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/App_payment/order.html
{% extends 'base.html' %}


{% block title %}
Order
{% endblock title %}



{% block body_block %}


<table class="table table-bordered">
    <thead>
        <th scope="col">#</th>
        <th scope="col">Order_id</th>
        <th scope="col">Products</th>
        <th scope="col">Total Amount</th>
        <th scope="col">Status</th>
    </thead>
    <tbody>
        {% for order in order_items %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{order.order_id}}</td>
            <td>
                {% for user_order in order.order_items.all %}
                <p>{{user_order.item.product_name}}</p>
                {% endfor %}
            </td>
            <td>&#2547; {{order.get_totals}}</td>
            
            <td><span class="badge text-bg-primary">{{order.status}}</span></td>
        </tr>
        {% endfor %}
    </tbody>

</table>

{% endblock body_block %}